### ISSUE TITLE
RNA004

### ISSUE THREAD

**Issue by mocherry** [haotianteng/Xron#3]
Dear developer,

I would like to ask whether Xron can be used for base-calling of RNA-sequencing data obtained from RNA004 direct RNA-Seq runs. Data are either *.fast5 or *.pod5.

Thanks and best
Matthias

**Comment by haotianteng** [comment]
We are tensely working on it, keep tight!

**Comment by haotianteng** [comment]
Hi we have released the RNA004 model trained on HEK293T cell line! See the README for how to use it.
