### ISSUE TITLE
xron-samples folder is missing

### ISSUE THREAD

**Issue by abcdtree** [haotianteng/Xron#5]
Hi Dear author,

It says 
`We provided sample code in xron-samples folder to achieve m6A-aware basecall and identify m6A site.`
in the document, but I did not find the xron-samples folder in both github and python lib.

has it been deleted?

Cheers,
Josh

**Comment by haotianteng** [comment]
Hi, the xron-samples folder has been uploaded, the document will be updated with our manuscript.
