### ISSUE TITLE
Model downloading

### ISSUE THREAD

**Issue by PengNi** [haotianteng/Xron#6]
Hi @haotianteng ,

Great tool! I want to use it now but I have problem of downloading the models.

When using `xron init` and `wget https://xronmodel.s3.us-east-1.amazonaws.com/models.zip`, both show a `403: Forbidden Error`.
```shell
wget https://xronmodel.s3.us-east-1.amazonaws.com/models.zip
```
```
--2024-11-01 08:50:16--  https://xronmodel.s3.us-east-1.amazonaws.com/models.zip
正在解析主机 xronmodel.s3.us-east-1.amazonaws.com (xronmodel.s3.us-east-1.amazonaws.com)... 52.217.204.82, 52.216.53.250, 52.217.194.66, ...
正在连接 xronmodel.s3.us-east-1.amazonaws.com (xronmodel.s3.us-east-1.amazonaws.com)|52.217.204.82|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 403 Forbidden
2024-11-01 08:50:17 错误 403：Forbidden。
```

May you provide another way for model downloading?

Thanks a lot!

Best,
Peng

**Comment by MSajek** [comment]
I have the same error, any suggestions how to fix it?

**Comment by umahsn** [comment]
I am also having the same error.

**Comment by haotianteng** [comment]
Now, can you try again? It should be good to go.
We restricted the AWS ID for internal use prior to the publication of our paper.

**Comment by BrendanBeahan** [comment]
@haotianteng 

Looks good! I can download now.

**Comment by PengNi** [comment]
Thank haotian and all of you!

**Comment by sbridgett** [comment]
I've installed xron, but when I try the `xron init` or `wget https://xronmodel.s3.us-east-1.amazonaws.com/models.zip` step, I get the error: `ERROR 403: Forbidden` as below:

```
$ wget https://xronmodel.s3.us-east-1.amazonaws.com/models.zip
--2024-12-19 18:10:33--  https://xronmodel.s3.us-east-1.amazonaws.com/models.zip
Resolving xronmodel.s3.us-east-1.amazonaws.com (xronmodel.s3.us-east-1.amazonaws.com)... 16.182.98.34, 52.216.40.34, 52.217.93.96, ...
Connecting to xronmodel.s3.us-east-1.amazonaws.com (xronmodel.s3.us-east-1.amazonaws.com)|16.182.98.34|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-12-19 18:10:33 ERROR 403: Forbidden.
```
